development:
  adapter: postgresql
  encoding: unicode
  database: eventer_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: eventer_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: eventer_production
  pool: 5
  username: postgres
  password: postgres
